import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import tailwind from '@astrojs/tailwind';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import vercel from '@astrojs/vercel/serverless';

// https://astro.build/config
export default defineConfig({
  site: 'https://khanmeditour.com',
  output: 'hybrid',
  adapter: vercel(),
  // Reason: route renamed from /for to /countries pre-deployment; redirects keep
  // old preview links and browser history working. (status: 301 = permanent)
  redirects: {
    '/for': { status: 301, destination: '/countries' },
    '/for/[country]': { status: 301, destination: '/countries/[country]' },
    // Reason: /bn/countries now has real Bengali pages (Bangladesh) and a
    // Bengali directory page. Non-translated country slugs under /bn/countries/
    // are not generated by getStaticPaths and will 404 — the Bengali directory
    // links those countries to their English pages instead.
  },
  integrations: [
    react(),
    tailwind({
      applyBaseStyles: false,
      configFile: './tailwind.config.ts',
    }),
    mdx(),
  ],
  i18n: {
    locales: ['en', 'bn'],
    defaultLocale: 'en',
    routing: {
      prefixDefaultLocale: false,
    },
  },
  vite: {
    resolve: {
      alias: {
        '@ds': '/src/design-system',
        '@features': '/src/features',
        '@lib': '/src/lib',
      },
    },
  },
});
